chore: 배포테스트2

diff --git a/.github/workflows/be-cicd.yml b/.github/workflows/be-cicd.yml
--- a/.github/workflows/be-cicd.yml
+++ b/.github/workflows/be-cicd.yml
@@ -27,7 +27,7 @@ jobs:
           key: ${{secrets.EC2_PEMKEY}}
           script: |
             if ! type docker > /dev/null ; then
-              sudo snap install docker || echo "docker install failed"
+              sudo snap install docker || echo "docker install failed!"
             fi
             sudo docker login --username ${{secrets.DOCKER_EMAIL}} --password ${{secrets.DOCKER_PASSWORD}}
             sudo docker-compose pull && sudo docker-compose up -d
